server:
  port: 11000
spring:
  application:
    name: gulimall-product
  datasource:
    username: root
    password: N48uVgRR
    url: jdbc:mysql://43.143.173.67:51806/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto